### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by SpacePossum**
Hi and thanks for making the PR on the main repo.

After reviewing I've made this PR, it aims to fix 3 issues, let me know what you think.

### CODE REVIEW

**Comment by SpacePossum** [comment]
ping @jrmajor   :)

**Comment by jrmajor** [comment]
Sorry, I must have missed notification :)

I understand that one issue is merging whitespace and the second is handling strangely-placed comments, what's the third one?

**Comment by SpacePossum** [comment]
Thanks for the merge :)

The 3rd is about the tokens collection and removing a token from it. The tokens collection or "stream" should never have consecutive "white space" tokens. As the tokens get passed on from rule to rule, each rule must be able to rely on this fact, as to simplify things. It is an edge case, but a nice one to have covered :+1:

**Comment by jrmajor** [comment]
That's what I meant by “merging whitespace”. Anyway, thank you for your help with this PR :)

**Comment by SpacePossum** [comment]
ah check :+1:  hmmmm .. I cannot see the 3rd one haha, got lost in my own PR here I'm afraid

**Pull request merged**
